"""empty message

Revision ID: 0e1c7f712cec
Revises: 4893590f5ac6
Create Date: 2023-04-17 21:39:54.452212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1c7f712cec'
down_revision = '4893590f5ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lang_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('date_created')
        batch_op.drop_column('lang_code')

    # ### end Alembic commands ###
