"""empty message

Revision ID: 4893590f5ac6
Revises: afefa58f0ce7
Create Date: 2023-04-17 21:01:00.264637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4893590f5ac6'
down_revision = 'afefa58f0ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_story_id'), ['story_id'], unique=False)
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posts_story_id'))
        batch_op.drop_column('story_id')

    op.drop_table('stories')
    # ### end Alembic commands ###
