"""empty message

Revision ID: 64f34ece1bd1
Revises: 20c3bdf30f91
Create Date: 2023-04-26 16:16:16.532921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64f34ece1bd1'
down_revision = '20c3bdf30f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edit_note', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('last_edit_note')

    # ### end Alembic commands ###
