"""empty message

Revision ID: 766549d69f5e
Revises: f795a56c5328
Create Date: 2023-03-19 10:12:29.299881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766549d69f5e'
down_revision = 'f795a56c5328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('get_comment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('get_comment')

    # ### end Alembic commands ###
