"""empty message

Revision ID: 76bed5892913
Revises: 64f34ece1bd1
Create Date: 2023-04-26 21:20:04.338252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76bed5892913'
down_revision = '64f34ece1bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_note', sa.String(length=500), nullable=True))
        batch_op.drop_column('last_edit_note')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_edit_note', mysql.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('author_note')

    # ### end Alembic commands ###
