"""empty message

Revision ID: afefa58f0ce7
Revises: 94b53d2f0927
Create Date: 2023-04-05 09:18:42.597158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afefa58f0ce7'
down_revision = '94b53d2f0927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('resume_html')

    # ### end Alembic commands ###
